const POSTS = [
    {
        id: "1",
        userName: "Donte Edwards",
        userHandle: "dontaaaayyyyy13",
        userAvatar: "https://media.them.us/photos/5a0497d33614d6000b69e8c0/master/w_1600%2Cc_limit/GettyImages-694901786.jpg",
        postPhoto:"https://upload.wikimedia.org/wikipedia/commons/8/88/Perfect_black_pride_guy_%287107944497%29.jpg",
        postCaption:"We All Need Love",
        postLikes: "44", 
    },
    {
        id: "2",
        userName: "Brenton West",
        userHandle: "westendbren",
        userAvatar: "https://www.thegentlemanblogger.com/wp-content/uploads/2018/03/MatthewZorpasBLOGSIZE-21.jpg",
        postPhoto:"https://www.thegentlemanblogger.com/wp-content/uploads/2018/03/MatthewZorpasBLOGSIZE-21.jpg",
        postCaption:"Street Style Revolutionized",
        postLikes: "1,378",
    },
    {
        id: "3",
        userName: "Nelson Dalton",
        userHandle: "thenelsondalton",
        userAvatar: "https://www.thefashionspot.com/assets/uploads/gallery/mens-fashion-blogs-2018/screen-shot-2018-02-28-at-12-58-16-pm.png",
        postPhoto:"https://www.food.ee/wp-content/uploads/2017/08/foodbloggers.jpg",
        postCaption:"Treat Your Body As Well As You Treat Your Mom ",
        postLikes: "70",
    },
    {
        id: "4",
        userName: "Marissa Contreras",
        userHandle: "4tresrissa",
        userAvatar: "https://i.pinimg.com/originals/67/e6/3a/67e63acd85db751876833fd84be06afc.jpg",
        postPhoto:"https://i.pinimg.com/originals/67/e6/3a/67e63acd85db751876833fd84be06afc.jpg",
        postCaption:"Fun in This LA Sun",
        postLikes: "491",
    },
    {
        id: "5",
        userName: "Kaleb Haney",
        userHandle: "hahahaney33",
        userAvatar: "https://www.meanwhileinawesometown.com/wp-content/uploads/2016/09/Travel-Diary-New-York-Williamsburg-Brooklyn-East-Village-Manhattan-by-Meanwhile-in-Awesometown-Austrian-Mens-Fashion-and-Lifestyle-Blogger16.jpg",
        postPhoto:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/lifestyle-bestdogbreeds-1577128927.png",
        postCaption:"Let Me Tell You Bout My BESTFRIEND",
        postLikes: "4,629",
    },
    {
        id: "6",
        userName: "Dominik Knox",
        userHandle: "knoxville213",
        userAvatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Q3PAF3xb39C29eI1CgW6nffzjChaWAEU0A&usqp=CAU",
        postPhoto:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9Q3PAF3xb39C29eI1CgW6nffzjChaWAEU0A&usqp=CAU",
        postCaption:"I Do It For Yall",
        postLikes: "11,358",
    },
    {
        id: "7",
        userName: "Riley Villarreal",
        userHandle: "RileyRealyVill",
        userAvatar: "https://www.wweek.com/resizer/pfsgEKjVzeiQMh1n7YtsU3J98oA=/1200x0/filters:quality(100)/s3.amazonaws.com/arc-wordpress-client-uploads/wweek/wp-content/uploads/2020/08/11140019/chri738-242-Edit-2_WEB-e1597269771340.jpg",
        postPhoto:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsIxUlrtFW9A_ZSbIiK8Llqu9YN_TmR4_jyw&usqp=CAU",
        postCaption:"You Can Get A Taste!",
        postLikes: "13",
    },
    {
        id: "8",
        userName: "Arda Vang",
        userHandle: "catchmyvangs",
        userAvatar: "https://media.theeverygirl.com/wp-content/uploads/2015/03/budget-friendly-fashion-bloggers-17.jpg",
        postPhoto:"https://yesmissy.com/wp-content/uploads/2019/03/toronto-fashion-blogger-lace-top-beige-pant-pink-bucket-bag-810x1013.jpg",
        postCaption:"Youve Been SERVED Lewks",
        postLikes: "88",
    },
    {
        id: "9",
        userName: "Mariah Mcgill",
        userHandle: "mcgilllllll",
        userAvatar: "https://mediakix.com/wp-content/uploads/2018/01/yoga-influencer.jpg",
        postPhoto:"https://www.yogajournal.com/.image/t_share/MTczNjg4ODY0NTM0MTc3MzM4/img_20190510_073331_571.jpg",
        postCaption:"Bend With The Wind",
        postLikes: "188",
    },
    {
        id: "10",
        userName: "Teegan Rush",
        userHandle: "TeeMoney94",
        userAvatar: "https://i2.wp.com/www.dailycal.org/assets/uploads/2019/06/coloredited_emilybi_rapper-900x580.png",
        postPhoto:"https://cdn.i-scmp.com/sites/default/files/styles/1200x800/public/d8/images/methode/2020/06/29/3b8850c4-b74c-11ea-94a5-08ba74052128_image_hires_130055.jpg?itok=tjyXjfWi&v=1593406864",
        postCaption:"Im Just Here",
        postLikes: "23,016",
    },
    {
        id: "11",
        userName: "Sultan Perez",
        userHandle: "themightysultan",
        userAvatar: "https://i.pinimg.com/originals/08/07/79/0807793001d793bec1ba3220597b7828.jpg",
        postPhoto:"https://i.pinimg.com/originals/08/07/79/0807793001d793bec1ba3220597b7828.jpg",
        postCaption:"Looking Forward To This New Chapter In Life",
        postLikes: "51",
    },
    {
        id: "12",
        userName: "Hari Evans",
        userHandle: "dontbehari",
        userAvatar: "https://contentmode.typepad.com/.a/6a0120a6a14ab5970c0148c8318d49970c-pi",
        postPhoto:"https://www.theurbangent.com/wp-content/uploads/2011/05/copenhagen-street-style.jpeg",
        postCaption:"City Life City Nights",
        postLikes: "72",
    },
    {
        id: "13",
        userName: "Kayden Pritchard",
        userHandle: "PrityKayden",
        userAvatar: "https://images.squarespace-cdn.com/content/v1/5ae63d7c8f51303ed37a8ab3/1568204611871-A7G7EUREQ5YEV8D0JT2N/ke17ZwdGBToddI8pDm48kEVz9t0k3W--_e2nHkU0dZJ7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QHyNOqBUUEtDDsRWrJLTmihaE5rlzFBImxTetd_yW5TFNbuEmGMMx33nit_OB_Y3OjNagxey-x4NFG3qDK-pN/How+My+Yoga+Practice+Has+Evolved+Over+the+Years+%7C+In+this+post%2C+I+share+how+I+found+yoga%2C+how+it+helped+me+and+how+it+fits+into+my+life+today.+As+I+reflect+on+this+evolution%2C+I+feel+immense+gratitude.+Just+as+yoga+has+been+there+for+me%2C+Athleta+has+been+there+since+the+beginning+of+my+entrepreneurial+efforts.+Yoga+is+my+foundation.+I+turn+to+my+mat+when+I+need+to+get+out+of+my+head.+%23yogaposes+%23yogainspiration+%23yogaoutfit+%23yogablogger+%23morningyoga+%23reflection+%23gratitudejournal+%23athleta",
        postPhoto:"https://breakbrunch.com/wp-content/uploads/2019/11/cute-bright-smile-112419.jpg",
        postCaption:"Stealing My Heart",
        postLikes: "506", 
    },
    {
        id: "14",
        userName: "Troy Braun",
        userHandle: "BraunBo67",
        userAvatar: "https://lh3.googleusercontent.com/proxy/Xq_iaBK3JSc1j1GrgorjyYY069_u5k22QASA94uUwtujmSvclkfyH-5Gi8tTS_3TZhsBA1-hPXE94ZGAzG7MGZwFi9e-Jbmd7Os9Zh2ZlBTSVjG3kOlhRnA",
        postPhoto:"https://i.pinimg.com/originals/b6/fc/1a/b6fc1aabe4c415fe58fb811b777e5b72.jpg",
        postCaption:"Fit Life For Life",
        postLikes: "65", 
    },
    {
        id: "15",
        userName: "Tashan Chaney",
        userHandle: "ChaChaTashan",
        userAvatar: "https://fashionista.com/.image/t_share/MTQwMjM3MjM0NDU1NTIwNDg4/taye-stuff-she-likes-1jpg.jpg",
        postPhoto:"https://fashionista.com/.image/t_share/MTQwMjM3MjM0NDU1NTIwNDg4/taye-stuff-she-likes-1jpg.jpg",
        postCaption:"Concrete Jungle Where Dreams Are Made Of",
        postLikes: "334",
    },
   
  ];

export default POSTS;