import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    
    rowCenter:{
        alignItems: 'center',
    },
    headerContainer: {
        flex: 1,
        flexDirection: "row",
        backgroundColor: '#dcedc8',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 15,
    },
    headerItem: {
        flexDirection: "row",
        alignItems: 'center',
    },
    headerText: {
        color: 'black',
        fontSize: '50px',
    },
    headerArrow: {
        color: 'black',
        padding: 5,
    },
    headerLogo: {
        width: '30vw',
        height: '5vw',
        resizeMode: "contain",
    },
    baseContainer:{
        flex: 1,
        backgroundColor: '#ededed',
        padding: 10,
    },
    rowStory:{
        flex: 1,
        flexDirection: "row",
        justifyContent: 'space-between',
        padding: '2vw',
        margin: '.5vw',
    },
    storyImage:{
        width: '7vw',
        height: '7vw',
        borderRadius: '50%',
        border: '3px solid #555',
    },
    storyText:{
        color: '#546e7a',
        fontSize: '1.5vw',
        fontWeight: '300',
        maxWidth: '20vw',
    },
    rowPost:{
        flex: 1,
        flexDirection: "row",
        justifyContent: 'center',
        padding: 15,
    },
    postCard:{
        backgroundColor: '#fffffb',
        padding: 20,
        borderRadius: 20,
    },
    postImage:{
        width: '7vw',
        height: '7vw',
        borderRadius: '50%',
        border: '3px solid #555',
        marginRight: 10,
    },
    postText:{
        color: '#546e7a',
        fontSize: '2.5vw',
        fontWeight: '300',
        maxWidth: '20vw',
        alignSelf: 'center',
    },
    postImage2:{
        width: '50vw',
        height: '50vw',
        marginBottom: 10,
    },
    postText2:{
        color: '#546e7a',
        fontSize: '1.5vw',
        maxWidth: '20vw',
        alignSelf: 'center',
    },
    postText3:{
        color: '#546e7a',
        fontSize: '1.5vw',
        fontWeight: '300',
        maxWidth: '20vw',
        marginLeft: 10,
    },
    rowFollow:{
        flex: 1,
        flexDirection: "row",
        justifyContent: 'center',
        padding: 30,
    },
    followImage:{
        width: '7vw',
        height: '7vw',
        borderRadius: '50%',
        border: '1px solid #555',
        marginBottom: 5,
    },
    followText:{
        color: '#546e7a',
        fontSize: '2vw',
        fontWeight: '300',
        maxWidth: '20vw',
        marginBottom: 5,
    },
    followCard:{
        backgroundColor: '#fffffb',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    rowGrid:{
        flex: 1,
        flexDirection: "row",
        justifyContent: 'space-between',
    },
    gridImage:{
        width: '32vw',
        height: '32vw',
        marginBottom: '.3vw',
    },
    exploreSearchBar:{
        width: '90vw',
        height: '5vw',
        paddingLeft: 20,
        backgroundColor: '#fffffb',
        borderRadius: 20,
    },
    exploreSearchContainer:{
        flex: 1, 
        alignItems: 'center', 
        marginBottom: 30, 
        marginTop: 20,
    },
    notifiContainer:{
        backgroundColor: '#fffffb',
        padding: 10,
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '90vw',
        alignSelf: 'center',
        marginBottom: 5,
    },
    notifiText:{
        color: '#546e7a',
        fontSize: '5vw',
        marginBottom: 20,
    },
    notifiText2:{
        color: '#546e7a',
        fontSize: '2vw',
        fontWeight: '300',
        alignSelf: 'center',
        marginLeft: 20,
    },
    notifiImage:{
        width: '5vw',
        height: '5vw',
        borderRadius: '50%',
        border: '1px solid #555',
        marginBottom: 5,
    },
    profileContainer:{
        flex: 1,
        backgroundColor: '#fffffb',
        padding: 10,
    },
    profileImage:{
        width: '10vw',
        height: '10vw',
        borderRadius: '50%',
        border: '1px solid #555',
        marginBottom: 5,
        marginLeft: 25,
    },
    profileText1:{
        color: '#546e7a',
        fontSize: '2.5vw',
        marginBottom: 5,
        alignSelf: 'center',
    },
    profileText2:{
        color: '#546e7a',
        fontSize: '2vw',
        fontWeight: '300',
        maxWidth: '40vw',
        marginBottom: 5,
        marginLeft: 25,
    },
    profileStoryRow:{
        flex: 1,
        flexDirection: "row",
        justifyContent: 'space-between',
        padding: '2.5vw',
        margin: '.5vw',
    },
    profileStoryImage:{
        width: '7vw',
        height: '7vw',
        borderRadius: '50%',
        border: '3px solid #555',
    },
    profileStoryText:{
        color: '#546e7a',
        fontSize: '1.5vw',
        fontWeight: '300',
        maxWidth: '20vw',
    },
});
export default styles;